[Data]
TempDir = "var/lib/tmp/output"

[PretrainedModels]
modelDir = "var/lib/pretrained_models"
modelSupported = ['ffhq.pkl']
SDVersion = "./models/stable-diffusion-v1-5"

[Scheduler]
JobDir = "var/lib/tmp/jobs"
MaxLogLines = 500
LogLevel = "debug"
